name: 'PageSpeed Report for Shopify'
description: 'Run PageSpeed Insights on a Shopify store and send the report to a Google Cloud Function.'
inputs:
  project:
    description: 'The JIRA project ID.'
    required: true
    default: 'CHANGEME'
  store:
    description: 'The Shopify store URL.'
    required: true
    default: 'changeme.myshopify.com'
  access_token:
    description: 'The Shopify access token.'
    required: true
  # commit hash to identify the change responsible for this test
  commit_hash:
    description: 'The git commit hash.'
    required: true
  # branch to group the results
  branch:
    description: 'The git branch.'
    required: true
  sa_key:
    description: 'The Google Cloud service account key.'
    required: true
  runs:
    description: 'How many times to repeat each PageSpeed test (min 1, max 5).'
    required: false
    default: '3'
runs:
  using: 'composite'
  steps:
    - name: Run PageSpeed script
      shell: bash
      run: ${{ github.action_path }}/run.sh
      env:
        # GitHub Actions Run ID for traceability in downstream systems
        GITHUB_RUN_ID: ${{ github.run_id }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_COMMIT_HASH: ${{ inputs.commit_hash }}
        INPUT_PROJECT: ${{ inputs.project }}
        INPUT_STORE: ${{ inputs.store }}
        INPUT_ACCESS_TOKEN: ${{ inputs.access_token }}
        INPUT_SA_KEY: ${{ inputs.sa_key }}
        INPUT_RUNS: ${{ inputs.runs }}
