name: Performance tests (GCP)

on:
  schedule:
    - cron: '0 3 * * *' # run daily at 3 a.m. UTC
  workflow_dispatch:

jobs:
  pagespeed:
    name: PageSpeed Google Cloud Function
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run PageSpeed report
        uses: techdivision/rnd-shopify-pagespeed-report-github-action@main
        with:
          commit_hash: ${{ github.sha }}
          branch: ${{ github.ref_name }}
          project: ${{ secrets.JIRA_PROJECT }}
          store: ${{ secrets.SHOP_STORE_OS2 }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          sa_key: ${{ secrets.PAGESPEED_GOOGLE_CLOUD_SA_KEY }}
